# Generated by Django 4.2.6 on 2023-10-31 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=1000)),
                ('long_description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='images/${horse.name}/')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('strength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dam', to='cs3300_project.horse')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs3300_project.horse')),
                ('sire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sire', to='cs3300_project.horse')),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs3300_project.statistics'),
        ),
        migrations.CreateModel(
            name='BuyableHorse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cs3300_project.horse')),
            ],
        ),
    ]
