# Generated by Django 4.2.6 on 2023-11-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs3300_project', '0005_alter_horse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='pedigree',
            name='horse',
        ),
        migrations.AddField(
            model_name='horse',
            name='pedigree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cs3300_project.pedigree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='horse',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
