# Generated by Django 4.2.6 on 2023-11-01 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs3300_project', '0006_remove_horse_statistics_remove_pedigree_horse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='pedigree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cs3300_project.pedigree'),
        ),
    ]
