name: Django Coverage

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Django Coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.11
              uses: actions/setup-python@v3
              with:
                  python-version: 3.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Django Coverage action
              uses: dc740/django-coveragepy-github-action@0.9
              with:
                django-app: 'cs3300_project'
                minimum-coverage: '80'